### ISSUE TITLE
Trouble loading component guides

### ISSUE THREAD

**Issue by smiranda2368** [fabric-engine/Kraken#284]
Hello,

I've just installed Fabric and Kraken and am attempting to use the Component Guides, but am running into errors. Here's what the command line's spitting out:

Traceback (most recent call last):
  File "C:\alienbrainWork\FabricEngine\Kraken-kraken_v1.0.0\Python\kraken\ui\Gra
phView\kgraph_view.py", line 181, in dropEvent
    component = componentClass(parent=self.getRig())
  File "C:\alienbrainWork\FabricEngine\Kraken-kraken_v1.0.0\Python\kraken_exampl
es\clavicle_component.py", line 81, in __init__
    self.loadData(data)
  File "C:\alienbrainWork\FabricEngine\Kraken-kraken_v1.0.0\Python\kraken_exampl
es\clavicle_component.py", line 119, in loadData
    self.clavicleCtrl.xfo = data['clavicleXfo']
  File "C:\alienbrainWork\FabricEngine\Kraken-kraken_v1.0.0\Python\kraken\core\o
bjects\object_3d.py", line 75, in xfo
    self._xfo = value.clone()
  File "C:\alienbrainWork\FabricEngine\Kraken-kraken_v1.0.0\Python\kraken\core\m
aths\xfo.py", line 148, in clone
    xfo.tr = self.tr.clone();
  File "C:\alienbrainWork\FabricEngine\Kraken-kraken_v1.0.0\Python\kraken\core\m
aths\xfo.py", line 61, in tr
    return Vec3(self._rtval.tr)
  File "C:\alienbrainWork\FabricEngine\Kraken-kraken_v1.0.0\Python\kraken\core\m
aths\vec3.py", line 19, in __init__
    if ks.getRTValTypeName(x) == 'Vec3':
  File "C:\alienbrainWork\FabricEngine\Kraken-kraken_v1.0.0\Python\kraken\core\k
raken_system.py", line 204, in getRTValTypeName
    return json.loads(rtval.type("Type").jsonDesc("String"))['name']
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

I've confirmed that the prereqs are installed, not sure what I am missing... Any ideas?

-Stephen-

**Comment by EricTRocks** [comment]
Are you using Fabric 1.15.x? The 1.0 release only works with that version
of fabric.

**Comment by smiranda2368** [comment]
Thanks Eric, that was definitely the issue!
