### ISSUE TITLE
Maya attribute does not exist "unknown1.inputMatrix"

### ISSUE THREAD

**Issue by BigRoy** [fabric-engine/Kraken#299]
It seems that when `matrixNodes.mll` is not loaded in Maya's plug-in manager before building the rig with Kraken the following error occurs:

```python
Traceback (most recent call last):
  File "P:\NETRENDER\app_shared\Kraken\Python\kraken\ui\GraphView\kgraph_view_widget.py", line 229, in buildRig
    builder.build(rig)
  File "P:\NETRENDER\app_shared\Kraken\Python\kraken\core\builder.py", line 896, in build
    self._build(kSceneItem)
  File "P:\NETRENDER\app_shared\Kraken\Python\kraken\core\builder.py", line 875, in _build
    self.buildOperators(kSceneItem)
  File "P:\NETRENDER\app_shared\Kraken\Python\kraken\core\builder.py", line 689, in buildOperators
    self.buildOperators(child)
  File "P:\NETRENDER\app_shared\Kraken\Python\kraken\core\builder.py", line 680, in buildOperators
    self.buildKLOperator(operator)
  File "P:\NETRENDER\app_shared\Kraken\Python\kraken\plugins\maya_plugin\builder.py", line 687, in buildKLOperator
    connectOutput(str(spliceNode + "." + argName), connectionTargets['opObject'], connectionTargets['dccSceneItem'])
  File "P:\NETRENDER\app_shared\Kraken\Python\kraken\plugins\maya_plugin\builder.py", line 677, in connectOutput
    cmds.connectAttr(src, str(decomposeNode.attr("inputMatrix")))
  File "C:\Program Files\Autodesk\Maya2016\Python\lib\site-packages\pymel\core\nodetypes.py", line 479, in attr
    return self._attr(attr, False)
  File "C:\Program Files\Autodesk\Maya2016\Python\lib\site-packages\pymel\core\nodetypes.py", line 554, in _attr
    raise general.MayaAttributeError('%s.%s' % (self, attr))
MayaAttributeError: Maya Attribute does not exist (or is not unique):: u'unknown1.inputMatrix'
```

Shouldn't Kraken auto-load the plug-in if it requires it?

This could be done with

```python
import maya.cmds
maya.cmds.loadPlugin("matrixNodes", quiet=True)
```

**Comment by EricTRocks** [comment]
This is a great suggestion and yes it should. Will put this on the to do list.
