### ISSUE TITLE
"FABRIC_DFG_PATH" should indicate Presets/DFG in DCCIntegrations

### ISSUE THREAD

**Issue by yamahigashi** [fabric-engine/Kraken#346]
I pulled the current state of the develop2.x branch and have try to use the CanvasOperator (leg + foot components). 
In maya building phase, i got:

``` console
Traceback (most recent call last):
  File "D:\fabricengine\Exts\Kraken\Python\kraken\ui\GraphView\kgraph_view_widget.py", line 257, in buildRig
    rig.loadRigDefinition(rigBuildData)
  File "D:\fabricengine\Exts\Kraken\Python\kraken\core\objects\rig.py", line 166, in loadRigDefinition
    self._loadComponents(jsonData['components'])
  File "D:\fabricengine\Exts\Kraken\Python\kraken\core\objects\rig.py", line 97, in _loadComponents
    component = componentClass(name=componentData['name'], parent=self)
  File "D:\fabricengine\Exts\Kraken\Python\kraken_examples\foot_component.py", line 353, in __init__
    self.footPivotCanvasOp = CanvasOperator('footPivotCanvasOp', 'Kraken.Solvers.BipedFootPivotSolver')
  File "D:\fabricengine\Exts\Kraken\Python\kraken\core\objects\operators\canvas_operator.py", line 24, in __init__
    self.binding = host.createBindingToPreset(self.canvasPresetPath)
  File "D:\fabric\Python\2.7\FabricEngine\Core\CAPI.py", line 2883, in createBindingToPreset
    def createBindingToPreset(self, *args): return _CAPI.DFGHost_createBindingToPreset(self, *args)
Exception: Fabric: createBindingToPreset(execPath, argValues): presetPath 'Kraken.Solvers.BipedFootPivotSolver': no preset named 'Kraken.Solvers.BipedFootPivotSolver'

Error: Error Building; Fabric: createBindingToPreset(execPath, argValues): presetPath 'Kraken.Solvers.BipedFootPivotSolver': no preset named 'Kraken.Solvers.BipedFootPivotSolver'
```

I think that because of FABRIC_DFG_PATH. I modified DCCIntegrations/maya/Kraken.mod with
``` diff
diff --git a/DCCIntegrations/maya/Kraken.mod b/DCCIntegrations/maya/Kraken.mod
index bf854d6..d9a2aa4 100644
--- a/DCCIntegrations/maya/Kraken.mod
+++ b/DCCIntegrations/maya/Kraken.mod
@@ -2,5 +2,5 @@
 KRAKEN_PATH +:= ../../
 PYTHONPATH +:= ../../Python/
 FABRIC_EXTS_PATH +:= ../../Exts
-FABRIC_DFG_PATH +:= ../../Presets
+FABRIC_DFG_PATH +:= ../../Presets/DFG
 PATH +:= plug-ins
```

in softimage same thing.
``` diff
diff --git a/DCCIntegrations/softimage/Application/Plugins/Kraken_Plugin.py b/DCCIntegrations/softimage/Application/Plugins/Kraken_Plugin.py
index d8019ed..b29dd0b 100644
--- a/DCCIntegrations/softimage/Application/Plugins/Kraken_Plugin.py
+++ b/DCCIntegrations/softimage/Application/Plugins/Kraken_Plugin.py
@@ -44,9 +44,11 @@ def XSILoadPlugin(in_reg):
     if krakenExtsDir not in  os.environ['FABRIC_EXTS_PATH']:
         os.environ['FABRIC_EXTS_PATH'] = krakenExtsDir + os.pathsep + os.environ['FABRIC_EXTS_PATH']

-    canvasPresetsDir = os.path.join(krakenDir, 'CanvasPresets')
-    if canvasPresetsDir not in os.environ['FABRIC_DFG_PATH']:
+    canvasPresetsDir = os.path.join(krakenDir, 'Presets', 'DFG')
+    if 'FABRIC_DFG_PATH' in os.environ and canvasPresetsDir not in os.environ['FABRIC_DFG_PATH']:
         os.environ['FABRIC_DFG_PATH'] = canvasPresetsDir + os.pathsep + os.environ['FABRIC_DFG_PATH']
+    else:
+        os.environ['FABRIC_DFG_PATH'] = canvasPresetsDir

     krakenLoadMenu = os.getenv('KRAKEN_LOAD_MENU', 'True')
```
that seems ok.

is this reasonable?

**Comment by EricTRocks** [comment]
Yes thanks for finding this. I usually create a launcher .bat file on windows that sets these but users should also have these set by default via the plugins as you have done (or rather, fixed).

If you want to open a pull request with these changes I'll merge them in.
