### ISSUE TITLE
Kraken Hand Component fails to load

### ISSUE THREAD

**Issue by bhaux** [fabric-engine/Kraken#504]
# Traceback (most recent call last):
#   File "Z:\dist\fabric\releases\FabricEngine-2.5.0-Windows-x86_64_march10\Tools\Kraken\Python\kraken\ui\GraphView\contextual_node_list.py", line 159, in keyPressEvent
#     self.createNode()
#   File "Z:\dist\fabric\releases\FabricEngine-2.5.0-Windows-x86_64_march10\Tools\Kraken\Python\kraken\ui\GraphView\contextual_node_list.py", line 99, in createNode
#     component = componentClass(parent=self.graph.getRig())
#   File "Z:\dist\fabric\releases\FabricEngine-2.5.0-Windows-x86_64_march10\Tools\Kraken\Python\kraken_components\biped\hand_component.py", line 97, in __init__
#     self.loadData(self.default_data)
#   File "Z:\dist\fabric\releases\FabricEngine-2.5.0-Windows-x86_64_march10\Tools\Kraken\Python\kraken_components\biped\hand_component.py", line 145, in loadData
#     super(HandComponentGuide, self).loadData(data)
#   File "Z:\dist\fabric\releases\FabricEngine-2.5.0-Windows-x86_64_march10\Tools\Kraken\Python\kraken\core\objects\components\component.py", line 947, in loadData
#     attr.setValue(data[attr.getName()])
#   File "Z:\dist\fabric\releases\FabricEngine-2.5.0-Windows-x86_64_march10\Tools\Kraken\Python\kraken\core\objects\attributes\string_attribute.py", line 36, in setValue
#     super(StringAttribute, self).setValue(str(value))
#   File "Z:\dist\fabric\releases\FabricEngine-2.5.0-Windows-x86_64_march10\Tools\Kraken\Python\kraken\core\objects\attributes\attribute.py", line 57, in setValue
#     self._callback(value)
#   File "Z:\dist\fabric\releases\FabricEngine-2.5.0-Windows-x86_64_march10\Tools\Kraken\Python\kraken_components\biped\hand_component.py", line 359, in updateFingers
#     self.addFinger(finger)
#   File "Z:\dist\fabric\releases\FabricEngine-2.5.0-Windows-x86_64_march10\Tools\Kraken\Python\kraken_components\biped\hand_component.py", line 291, in addFinger
#     fingerGuideCanvasOp = CanvasOperator(name + 'FingerGuide', 'Kraken.Solvers.Biped.BipedFingerGuideSolver')
#   File "Z:\dist\fabric\releases\FabricEngine-2.5.0-Windows-x86_64_march10\Tools\Kraken\Python\kraken\core\objects\operators\canvas_operator.py", line 43, in __init__
#     portDataType = rtVal.getTypeName().getSimpleType()
# AttributeError: null reference

**Comment by EricTRocks** [comment]
This shouldn't happen any more with the latest changes from degas
